{
  "name": "surf-fed-electron",
  "version": "0.1.0",
  "description": "Surf FED desktop application",
  "main": "main.js",
  "homepage": "https://github.com/tT/Surf-FED",
  "author": {
    "name": "Surf FED",
    "email": "your-email@gmail.com"
  },
  "scripts": {
    "start": "electron .",
    "test": "electron --no-sandbox tests/run-test.js",
    "dist": "electron-builder --publish never"
  },
  "build": {
    "appId": "com.surffed.app",
    "productName": "Surf FED",
    "files": [
      "**/*",
      "!dist",
      "!node_modules/.cache"
    ],
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ],
      "category": "Utility",
      "maintainer": "Surf FED <your-email@gmail.com>",
      "desktopName": "surf-fed",
      "syncDesktopName": true
    }
  },
  "devDependencies": {
    "electron": "^39.8.10",
    "electron-builder": "^26.15.3"
  }
}
